### PR TITLE
Debounce the ajax function

### PR DESCRIPTION
**Pull request by dojutsu-user**
If the user is typing continuously, there were many ajax requests which were not required but were still made and completed.
This PR cancels the previous ajax request (if it is still in process) before making a new one.

Demo:

Peek 2019-06-25 15-50

### CODE REVIEW

**Comment by ericholscher** [comment]
I believe there is another approach here, which doesn't fire a request until 50ms after the user's keypress. This will save our servers the work, because a cancelled request still happens on the backend. We should instead try and have fewer requests sent to the server.

**Comment by dojutsu-user** [comment]
@ericholscher 
Yeah... `debouncing` the request.
@davidfischer told me about this, but this escapes my mind. I will update the PR.

**Comment by davidfischer** [comment]
You definitely want to debounce. UnderscoreJS (which Sphinx already includes) has a good implementation.

**Comment by dojutsu-user** [comment]
I will do it today.

**Comment by dojutsu-user** [comment]
Closed and reopened for the travis.

**Comment by dojutsu-user** [comment]
@davidfischer 
Underscore.js provides a debounce function but the version which Sphinx is using don't have a `cancel` method defined on debounced function.
`cancel` method was added after the release of `1.8.3` ([source](https://github.com/jashkenas/underscore/issues/2719#issuecomment-358242072)) and sphinx uses `1.3.1` (https://docs.readthedocs.io/en/stable/_static/underscore.js).
So I implemented a custom debounce function to get the work done.

I have updated the PR and the screenshot.

**Pull request merged**
